#RECUERDA QUE "NOTA" ES UNA VARIABLE, POR LO TANTO PUEDE CAMBIAR SU VALOR, EN ESTE CASO SE LE ASIGNA EL VALOR QUE EL USUARIO INGRESA POR TECLADO
#INT(INPUT()) ES UNA FUNCION QUE PERMITE CONVERTIR EL VALOR INGRESADO POR EL USUARIO EN UN NUMERO ENTERO
#YA QUE POR DEFECTO EL VALOR INGRESADO POR TECLADO ES UN STRING (TEXTO) 
#(INPUT() SIEMPRE DEVUELVE UN STRING), POR LO TANTO SE NECESITA CONVERTIRLO A UN NUMERO ENTERO PARA PODER REALIZAR LAS COMPARACIONES EN LOS CONDICIONALES


#if ES UNA ESTRUCTURA DE CONTROL DE FLUJO QUE PERMITE EJECUTAR UN BLOQUE DE CODIGO SI SE CUMPLE UNA CONDICION
# SI NO SE CUMPLE, SE PUEDE USAR EL ELIF (ELSE IF) PARA VERIFICAR OTRA CONDICION
# Y SI NINGUNA DE LAS CONDICIONES SE CUMPLE, SE PUEDE USAR EL ELSE PARA EJECUTAR UN BLOQUE DE CODIGO POR DEFECTO.
#RECUERDA ERES EL MEJOR, TU PUEDES!!!!

nota= int(input("Ingresa tu calificacion"))

if nota >=90:
    print("excelente")
elif nota >=60:
    print("aprobado")
else: 
    print("reprobado")

